### ISSUE TITLE
ExoPlayer no longer restarts at the stopped location

### ISSUE THREAD

**Issue by mackbagg** [OpenSageTV/sagetv-miniclient#86] opened 2018-10-03 00:37 UTC
If you press stop anywhere in a video using ExoPlayer it won't restart at that location and just starts at the beginning. The line position stays white up to the portion where it was stopped.

IJKPlayer doesn't exhibit this behavior. It happens on both my Mii and my Shield since version 1.3.0.

Thanks,
Mack

**Comment by stuckless** [comment] 2018-12-16 23:24
Can you test in 1.3.5?  I did do some tweaks to seeking/resume in 1.3.5.  I can't reproduce this issue locally.

**Comment by mackbagg** [comment] 2018-12-17 00:36
I Just tested it on the Shield TV and it still has the same problem. Sometimes it will work but most the time it doesn't. It does it on my Shield TV, a Fire TV stick, a Fire TV 4k stick, an older Mi Box and the newer Mi Box. I also tested it after turning off all my plugins which aren't that many to start with. I can stop and restart fine with IJKPlayer still.

**Comment by stuckless** [comment] 2018-12-18 10:54
Could you set the Stream mode to PULL in the App Settings, and see if that makes any difference.

**Comment by mackbagg** [comment] 2018-12-18 17:41
It still seems to have the same issue. There has got to be something
different in our set ups since you don't see the problem.

All I have to do is skip forward a bit in any file and stop, then using the
resume most the time it goes back to the beginning.

I am using a Shield TV as my main device like you. I do normalize all my
content to MP4 with AAC audio so everything is consistent other than direct
recordings.

Thanks,
Mack

**Comment by jvl711** [comment] 2020-08-25 12:58
@mackbagg 

I believe this issue was fixed in a recent version.  Please let me know if I am wrong and I will reopen.

Josh

**Closed as completed by jvl711** 2020-08-25 12:58 UTC
